# This is a basic workflow to help you get started with Actions
name: Release

env:
  PLUGIN_NAME: logseq-chess

permissions:
  contents: write

# Controls when the action will run.
on:
  # push:
  #   branches:
  #     - "master"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn build
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
